language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsbko
  api_key:
    secure: MJPbhWNRXFvO/S4+ptEwsoyN+Db+a9xRReQx4DJ54N/ip9EyZn3XXCCWdwUctU1l/xFG5KU+H/vZshvg9NHs2Fzf9IyIts11VRwp+iKkzJNQnlSQ0fk79v1WGrKYoQmzotDq46RomXQSHzZ+uPg0iuym34z8GbcR+zCkXT4F3JGuu0/l0JngWbbYKU6HXgkh5pmVCmGvTpgZUZ+TKRxGVgIcXvdQaRmjngx2h3q8kwHmWBOKS32l3zk7BV5L6Ymz8HU7HdYl18gglHAjLJp9aqJRTD8HAkAP73d2iDIPMdvyEsCRbp1uwUVJ6ArpoPmgMlRVK89bZOjgUdg/VnsbjhUC9CH8npYulAQXCuf2VjUQCmXjRhZPmIeny2a8rRkE2aARBtkBTKl/JMBJqqf/+qYU/XciZSFBOpN0uWvsC2e1sQhPtZoAPx0sKdcoUhec6KZ646lV0mje6qGXv1VfBmgYvqewrqGwIU8aJwnJ10x6PfLtHer1vYD6NFmxbi5dwR+i2okChxzwFeYRWAMJ8ewgPkIUYzLTyI4edRSRnHixRcMkwnOYgiMPn9/XFz/APfIIN1cS/cTxoiLc7CVo/GUZ9vX1tdBE8uaCuaaeW1lUMRKSZS8Fkls/bJX/yE7W+VUekGMYZv4+0VtQdQy1tn6LA3CBDBaw0Qc1k3SE0Z8=
